name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace with your main development branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to prod url
        # main is the branch name where new code is pushed
        if: github.ref == 'refs/heads/main'

        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder:
            out # The folder the action should deploy.


            #for it to work for github pages. add followig props inside next.config.js file
            # output: 'export',
            # basePath: '/nextjs14-ci-cd',
            # assetPrefix: '/nextjs14-ci-cd/',

            # uses: peaceiris/actions-gh-pages@v3
            # with:
            #   github_token: ${{ secrets.GITHUB_TOKEN }}
            #   publish_dir: ./dist
            # publish_branch: prod-gh-pages  // by default it will create gh-pages branch and push everything of dist folder inside it.

            # - name: Deploy to dev url
            #   if: github.ref == 'refs/heads/develop'
            #   uses: peaceiris/actions-gh-pages@v3
            #   with:
            #     github_token: ${{ secrets.GITHUB_TOKEN }}
            #     publish_dir: ./dist
            #     # publish_branch: dev-gh-pages
